#! /bin/sh

### BEGIN INIT INFO
# Provides:          varnishncsa
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start HTTP accelerator ncsa log daemon
# Description:       This script provides logging for varnish on the ncsa format
### END INIT INFO

# Source function library
. /lib/lsb/init-functions

NAME=varnishncsa
DESC="HTTP accelerator log deamon"
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/varnish/varnishncsa.log

# Include defaults if available
if [ -f /etc/default/$NAME ] ; then
        . /etc/default/$NAME
fi

# If unset, or set to "0" or "no", exit
if [ -z "${VARNISHNCSA_ENABLED}" ] || \
   [ "${VARNISHNCSA_ENABLED}" = "0" ] || \
   [ "${VARNISHNCSA_ENABLED}" = "no" ]; then
  exit 0;
fi

test -x $DAEMON || exit 0

DAEMON_OPTS="-c -P $PIDFILE"

case "$1" in
	start)
		log_daemon_msg "Starting $DESC"
		${DAEMON} ${DAEMON_OPTS} | logger -p local3.info &
		;;
	stop)
		log_daemon_msg "Stopping $DESC"
		log_progress_msg $NAME
		if start-stop-daemon \
		   --stop --quiet --pidfile $PIDFILE --retry 10 \
		   --exec $DAEMON; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
        	;;
	restart|force-reload)
		$0 stop
		$0 start
        	;;
	*)
        	log_success_msg "Usage: $0 {start|stop|restart|force-reload}"
        	exit 1
        ;;
esac

exit 0
